// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFxkuxt2V5q22RLGBwC9swO4I6jIBTxWM',
    appId: '1:986294078734:web:11ee6a20290c8c4e8e9b5f',
    messagingSenderId: '986294078734',
    projectId: 'codelab-flutter-with-gemini',
    authDomain: 'codelab-flutter-with-gemini.firebaseapp.com',
    storageBucket: 'codelab-flutter-with-gemini.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMc8admsuOhxXHhGIyTIOz813TO1PaQ2Y',
    appId: '1:986294078734:android:9cdab120575b4f968e9b5f',
    messagingSenderId: '986294078734',
    projectId: 'codelab-flutter-with-gemini',
    storageBucket: 'codelab-flutter-with-gemini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ESdYBqASxqOgo2WoJF9n5crZfMkdwkk',
    appId: '1:986294078734:ios:b5c3b88065c98d3c8e9b5f',
    messagingSenderId: '986294078734',
    projectId: 'codelab-flutter-with-gemini',
    storageBucket: 'codelab-flutter-with-gemini.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallengeTcu2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ESdYBqASxqOgo2WoJF9n5crZfMkdwkk',
    appId: '1:986294078734:ios:b5c3b88065c98d3c8e9b5f',
    messagingSenderId: '986294078734',
    projectId: 'codelab-flutter-with-gemini',
    storageBucket: 'codelab-flutter-with-gemini.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallengeTcu2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFxkuxt2V5q22RLGBwC9swO4I6jIBTxWM',
    appId: '1:986294078734:web:18abb0d744089f4b8e9b5f',
    messagingSenderId: '986294078734',
    projectId: 'codelab-flutter-with-gemini',
    authDomain: 'codelab-flutter-with-gemini.firebaseapp.com',
    storageBucket: 'codelab-flutter-with-gemini.firebasestorage.app',
  );
}
