// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKq6aL-Om7Pz6ta0sUorwpIJ-sBkAi5FI',
    appId: '1:996765302538:web:a7e11aad6e54ea0b5544f3',
    messagingSenderId: '996765302538',
    projectId: 'medflow-tcu',
    authDomain: 'medflow-tcu.firebaseapp.com',
    storageBucket: 'medflow-tcu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHBZzNWuUNk7Lz_exQyBlL-ef9_oUU0g',
    appId: '1:996765302538:android:6c1e24c8fb27ee8f5544f3',
    messagingSenderId: '996765302538',
    projectId: 'medflow-tcu',
    storageBucket: 'medflow-tcu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMj828GyF96qDo7diS2ywclYumuVqn24',
    appId: '1:996765302538:ios:6fc598989ddc0f3c5544f3',
    messagingSenderId: '996765302538',
    projectId: 'medflow-tcu',
    storageBucket: 'medflow-tcu.firebasestorage.app',
    iosClientId: '996765302538-rv609epkq9bgfbg93769aa760f2aspoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutionChallengeTcu2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMj828GyF96qDo7diS2ywclYumuVqn24',
    appId: '1:996765302538:ios:6fc598989ddc0f3c5544f3',
    messagingSenderId: '996765302538',
    projectId: 'medflow-tcu',
    storageBucket: 'medflow-tcu.firebasestorage.app',
    iosClientId: '996765302538-rv609epkq9bgfbg93769aa760f2aspoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.solutionChallengeTcu2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKq6aL-Om7Pz6ta0sUorwpIJ-sBkAi5FI',
    appId: '1:996765302538:web:a7e11aad6e54ea0b5544f3',
    messagingSenderId: '996765302538',
    projectId: 'medflow-tcu',
    authDomain: 'medflow-tcu.firebaseapp.com',
    storageBucket: 'medflow-tcu.firebasestorage.app',
  );

}